### PR TITLE
wip: generate markdown doc from schema

### PR DESCRIPTION
**Pull request by z8674558**

### CODE REVIEW

**Comment by z8674558** [comment]
https://github.com/emqx/hocon/blob/d8b377cc65de332e26f15969dba70c00e9befff3/sample-schemas/emqx_schema.md

**Comment by zmstone** [comment]
Thank you for the PR.
I have few comments:

- It would be great if we can make a 'tree-view' fro the Structs header.
- types like this `emqx_schema:duration()` are not quite helpful to doc readers.
  maybe we need some more help from typerefl for type doc ?

**Comment by zmstone** [comment]
Would be nice to add struct field descriptions, and primitive-field descriptions like below:


### `cluster`
#### Description
Configurations for EMQ X cluster
#### Fields
name|type|default|description
----|----|----|----
name|<code>atom()</code>|emqxcl|Name of the cluster <br/>The name all nodes in the cluster agree to.
discovery|<code>atom()</code>|manual|Node descovery mechanism <br/> `manual`: Manually (or by scripting) add nodes to or delete nodes from cluster

**Comment by zmstone** [comment]
see #129

**Pull request closed without merging**
